# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(null=True, upload_to='tumbs/%Y/%m/%d/'),
        ),
    ]
