# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
