# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161019_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
